#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "codex" / "subcommands.json"


def load_registry() -> dict:
    return json.loads(REGISTRY_PATH.read_text())


def resolve_path(relative_path: str) -> Path:
    return REPO_ROOT / relative_path


def extract_frontmatter_value(skill_path: Path, field: str) -> str:
    content = skill_path.read_text()
    match = re.search(rf"(?m)^{re.escape(field)}:\s*(.+?)\s*$", content)
    if not match:
        raise ValueError(f"Missing {field} frontmatter in {skill_path}")
    return match.group(1).strip().strip("\"'")


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def remove_existing_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()


def build_relative_symlink_target(source: Path, destination: Path) -> str:
    return os.path.relpath(source, start=destination.parent)


def link_skill(source: Path, destination: Path) -> None:
    remove_existing_path(destination)
    destination.symlink_to(build_relative_symlink_target(source, destination))


def render_alias(entry: dict, target_path: Path) -> str:
    source_dir = Path(entry["source"])
    relative_target = os.path.relpath(
        target_path,
        start=(REPO_ROOT / source_dir),
    )
    description = extract_frontmatter_value(target_path, "description")
    license_name = extract_frontmatter_value(target_path, "license")
    return (
        "---\n"
        f'name: {entry["name"]}\n'
        f'description: "{description}"\n'
        f"license: {license_name}\n"
        "---\n\n"
        "# Codex Skill Export\n\n"
        "<!-- AUTO-GENERATED by scripts/codex_subcommands.py. -->\n\n"
        f"This export exists so Codex installs can expose `{entry['name']}` while keeping the canonical implementation in `{entry['target']}`.\n\n"
        f"Load and follow the canonical skill at `{relative_target}` exactly.\n"
    )


def command_generate() -> None:
    registry = load_registry()
    for entry in registry["install"]:
        target_path = resolve_path(entry["target"]) / "SKILL.md"
        if not target_path.is_file():
            raise FileNotFoundError(f"Canonical skill missing: {target_path}")

        source_path = resolve_path(entry["source"]) / "SKILL.md"
        ensure_parent(source_path)
        target_name = extract_frontmatter_value(target_path, "name")
        if entry["name"] == target_name:
            link_skill(target_path, source_path)
            continue
        remove_existing_path(source_path)
        source_path.write_text(render_alias(entry, target_path))


def command_verify() -> None:
    registry = load_registry()
    prompt_path = resolve_path(registry["prompt"]["source"])
    if not prompt_path.is_file():
        raise FileNotFoundError(f"Missing prompt source: {prompt_path}")

    for entry in registry["install"]:
        source_path = resolve_path(entry["source"]) / "SKILL.md"
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing skill source: {source_path}")

        actual_name = extract_frontmatter_value(source_path, "name")
        if actual_name != entry["name"]:
            raise ValueError(
                f"Skill name mismatch for {source_path}: expected {entry['name']}, got {actual_name}"
            )

        target_path = resolve_path(entry["target"]) / "SKILL.md"
        if not target_path.is_file():
            raise FileNotFoundError(f"Missing canonical target: {target_path}")

        target_name = extract_frontmatter_value(target_path, "name")
        target_description = extract_frontmatter_value(target_path, "description")
        actual_description = extract_frontmatter_value(source_path, "description")
        if actual_description != target_description:
            raise ValueError(
                f"Description mismatch for {source_path}: expected canonical description"
            )

        if entry["name"] == target_name:
            if not source_path.is_symlink():
                raise ValueError(f"Canonical export is not symlinked: {source_path}")
            if source_path.resolve() != target_path.resolve():
                raise ValueError(f"Canonical export points to wrong target: {source_path}")
            continue

        expected = render_alias(entry, target_path)
        actual = source_path.read_text()
        if actual != expected:
            raise ValueError(f"Generated alias export is stale: {source_path}")


def link_path(source: Path, destination: Path) -> None:
    expected_target = build_relative_symlink_target(source, destination)
    if destination.exists() or destination.is_symlink():
        if destination.is_symlink() and destination.resolve() == source.resolve():
            if os.readlink(destination) == expected_target:
                return
            destination.unlink()
            destination.symlink_to(expected_target)
            return
        raise FileExistsError(f"Refusing to overwrite existing path: {destination}")
    destination.symlink_to(expected_target)


def build_manifest_entry(path: Path, codex_home: Path) -> str:
    return path.relative_to(codex_home).as_posix()


def resolve_manifest_path(path_text: str, codex_home: Path) -> Path:
    path = Path(path_text)
    if path.is_absolute():
        return path
    return codex_home / path


def command_install(codex_home: Path) -> None:
    command_generate()
    command_verify()
    registry = load_registry()

    skills_dir = codex_home / "skills"
    prompts_dir = codex_home / "prompts"
    skills_dir.mkdir(parents=True, exist_ok=True)
    prompts_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "skills": [],
        "prompts": [],
    }

    for entry in registry["install"]:
        source_dir = resolve_path(entry["source"])
        destination = skills_dir / source_dir.name
        link_path(source_dir, destination)
        manifest["skills"].append(build_manifest_entry(destination, codex_home))

    prompt_source = resolve_path(registry["prompt"]["source"])
    prompt_destination = codex_home / registry["prompt"]["target"]
    ensure_parent(prompt_destination)
    link_path(prompt_source, prompt_destination)
    manifest["prompts"].append(build_manifest_entry(prompt_destination, codex_home))

    (codex_home / ".pua-codex-install.json").write_text(json.dumps(manifest, indent=2))


def command_uninstall(codex_home: Path) -> None:
    manifest_path = codex_home / ".pua-codex-install.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"Missing install manifest: {manifest_path}. Nothing to uninstall safely."
        )

    manifest = json.loads(manifest_path.read_text())
    for path_text in manifest.get("skills", []):
        path = resolve_manifest_path(path_text, codex_home)
        if path.is_symlink():
            path.unlink()

    for path_text in manifest.get("prompts", []):
        path = resolve_manifest_path(path_text, codex_home)
        if path.is_symlink():
            path.unlink()

    manifest_path.unlink()

    for parent in (codex_home / "prompts", codex_home / "skills"):
        if parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Manage Codex namespaced PUA subcommands."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("generate", help="Generate Codex shim skills from the registry.")
    subparsers.add_parser("verify", help="Verify registry, canonical skills, and generated shims.")

    install = subparsers.add_parser("install", help="Install PUA Codex skills into a Codex home.")
    install.add_argument(
        "--codex-home",
        default="~/.codex",
        help="Target Codex home directory. Defaults to ~/.codex.",
    )

    uninstall = subparsers.add_parser(
        "uninstall", help="Remove PUA Codex skills previously installed by this script."
    )
    uninstall.add_argument(
        "--codex-home",
        default="~/.codex",
        help="Target Codex home directory. Defaults to ~/.codex.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "generate":
        command_generate()
        return

    if args.command == "verify":
        command_verify()
        return

    codex_home = Path(args.codex_home).expanduser().resolve()
    if args.command == "install":
        command_install(codex_home)
        return

    if args.command == "uninstall":
        command_uninstall(codex_home)
        return

    parser.error(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    main()
